services:
  - type: worker
    name: sleme-bot-worker
    runtime: python
    environment: python
    branch: main
    startCommand: python main.py
    buildCommand: pip install python-telegram-bot requests pillow
    envVars:
      - key: BOT_TOKEN
        value: 8696706532:AAEN6IwwzJ9J5DqXhYeUyqVKwM3okGtXOa8
